name: Deploy Primary Resources

description: "Deploy the primary resources for the application such as API Gateway, Lambda functions, DynamoDB tables, S3 buckets with CDN and more"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.APP_NAME }}-github-oidc-role
        role-session-name: ${{ env.APP_NAME }}-github-oidc-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Dependencies
      run: |
        export CI=true
        npm cache clean --force
        npm install
      shell: bash

    - name: Debug CDK Assets
      run: |
        npx cdk synth
        find cdk.out -name "*.zip" -exec du -sh {} +
        for zip in $(find cdk.out -name "*.zip"); do
          echo "Inspecting $zip"
          unzip -l "$zip" | awk '{print $1, $2, $3, $4, $5}' | sort -rh | head -20
        done
        du -sh cdk.out
      shell: bash



    - name: CDK deployment
      run: |
        npx cdk deploy ${{ env.APP_NAME }}-primary-resources-stack --exclusively --output cdk.primary.out --verbose --qualifier ${{ env.CDK_QUALIFIER }} --require-approval never
      shell: bash
