name: Deploy Primary Resources

description: "Deploy the primary resources for the application such as API Gateway, Lambda functions, DynamoDB tables, S3 buckets with CDN and more"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.APP_NAME }}-github-oidc-role
        role-session-name: ${{ env.APP_NAME }}-github-oidc-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: CDK deployment
      run: |
        export CI=true
        npm ci --only=production
        npx cdk deploy ${{ env.APP_NAME }}-primary-resources-stack --exclusively --output cdk.primary.out --verbose --qualifier ${{ env.CDK_QUALIFIER }} --require-approval never
      shell: bash
