name: Deploy Core Resources

description: "Deploy the core resources for the application including VPC, subnets, route tables, internet gateway, IAM roles and more"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.APP_NAME }}-github-oidc-role
        role-session-name: ${{ env.APP_NAME }}-github-oidc-session
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Docker
      run: |
        brew install --cask docker
        open -a Docker
      shell: bash

    - name: Wait for Docker to Start
      run: |
        while ! docker system info > /dev/null 2>&1; do
          echo "Waiting for Docker to start..."
          sleep 5
        done
      shell: bash

    - name: CDK deployment
      run: |
        export CI=true
        npm ci
        npx cdk deploy ${{ env.APP_NAME }}-core-resources-stack --exclusively --output cdk.core.out --verbose --qualifier ${{ env.CDK_QUALIFIER }} --require-approval never
      shell: bash
